/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bses.connection2.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ConnectionDocument service. Represents a row in the &quot;bsesconn_ConnectionDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.bses.connection2.model.impl.ConnectionDocumentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.bses.connection2.model.impl.ConnectionDocumentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConnectionDocument
 * @generated
 */
@ProviderType
public interface ConnectionDocumentModel
	extends BaseModel<ConnectionDocument>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a connection document model instance should use the {@link ConnectionDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this connection document.
	 *
	 * @return the primary key of this connection document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this connection document.
	 *
	 * @param primaryKey the primary key of this connection document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this connection document.
	 *
	 * @return the uuid of this connection document
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this connection document.
	 *
	 * @param uuid the uuid of this connection document
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the connection document ID of this connection document.
	 *
	 * @return the connection document ID of this connection document
	 */
	public long getConnectionDocumentId();

	/**
	 * Sets the connection document ID of this connection document.
	 *
	 * @param connectionDocumentId the connection document ID of this connection document
	 */
	public void setConnectionDocumentId(long connectionDocumentId);

	/**
	 * Returns the group ID of this connection document.
	 *
	 * @return the group ID of this connection document
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this connection document.
	 *
	 * @param groupId the group ID of this connection document
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this connection document.
	 *
	 * @return the company ID of this connection document
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this connection document.
	 *
	 * @param companyId the company ID of this connection document
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this connection document.
	 *
	 * @return the user ID of this connection document
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this connection document.
	 *
	 * @param userId the user ID of this connection document
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this connection document.
	 *
	 * @return the user uuid of this connection document
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this connection document.
	 *
	 * @param userUuid the user uuid of this connection document
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this connection document.
	 *
	 * @return the user name of this connection document
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this connection document.
	 *
	 * @param userName the user name of this connection document
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this connection document.
	 *
	 * @return the create date of this connection document
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this connection document.
	 *
	 * @param createDate the create date of this connection document
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this connection document.
	 *
	 * @return the modified date of this connection document
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this connection document.
	 *
	 * @param modifiedDate the modified date of this connection document
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the connection request ID of this connection document.
	 *
	 * @return the connection request ID of this connection document
	 */
	public long getConnectionRequestId();

	/**
	 * Sets the connection request ID of this connection document.
	 *
	 * @param connectionRequestId the connection request ID of this connection document
	 */
	public void setConnectionRequestId(long connectionRequestId);

	/**
	 * Returns the document type of this connection document.
	 *
	 * @return the document type of this connection document
	 */
	@AutoEscape
	public String getDocumentType();

	/**
	 * Sets the document type of this connection document.
	 *
	 * @param documentType the document type of this connection document
	 */
	public void setDocumentType(String documentType);

	/**
	 * Returns the document name of this connection document.
	 *
	 * @return the document name of this connection document
	 */
	@AutoEscape
	public String getDocumentName();

	/**
	 * Sets the document name of this connection document.
	 *
	 * @param documentName the document name of this connection document
	 */
	public void setDocumentName(String documentName);

	/**
	 * Returns the document path of this connection document.
	 *
	 * @return the document path of this connection document
	 */
	@AutoEscape
	public String getDocumentPath();

	/**
	 * Sets the document path of this connection document.
	 *
	 * @param documentPath the document path of this connection document
	 */
	public void setDocumentPath(String documentPath);

	/**
	 * Returns the transfered of this connection document.
	 *
	 * @return the transfered of this connection document
	 */
	@AutoEscape
	public String getTransfered();

	/**
	 * Sets the transfered of this connection document.
	 *
	 * @param transfered the transfered of this connection document
	 */
	public void setTransfered(String transfered);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ConnectionDocument connectionDocument);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ConnectionDocument> toCacheModel();

	@Override
	public ConnectionDocument toEscapedModel();

	@Override
	public ConnectionDocument toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}