/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bses.connection2.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the OTP service. Represents a row in the &quot;bsesconn_OTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.bses.connection2.model.impl.OTPModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.bses.connection2.model.impl.OTPImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OTP
 * @generated
 */
@ProviderType
public interface OTPModel
	extends BaseModel<OTP>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a otp model instance should use the {@link OTP} interface instead.
	 */

	/**
	 * Returns the primary key of this otp.
	 *
	 * @return the primary key of this otp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this otp.
	 *
	 * @param primaryKey the primary key of this otp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this otp.
	 *
	 * @return the uuid of this otp
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this otp.
	 *
	 * @param uuid the uuid of this otp
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the otp ID of this otp.
	 *
	 * @return the otp ID of this otp
	 */
	public long getOtpId();

	/**
	 * Sets the otp ID of this otp.
	 *
	 * @param otpId the otp ID of this otp
	 */
	public void setOtpId(long otpId);

	/**
	 * Returns the group ID of this otp.
	 *
	 * @return the group ID of this otp
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this otp.
	 *
	 * @param groupId the group ID of this otp
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this otp.
	 *
	 * @return the company ID of this otp
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this otp.
	 *
	 * @param companyId the company ID of this otp
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this otp.
	 *
	 * @return the user ID of this otp
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this otp.
	 *
	 * @param userId the user ID of this otp
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this otp.
	 *
	 * @return the user uuid of this otp
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this otp.
	 *
	 * @param userUuid the user uuid of this otp
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this otp.
	 *
	 * @return the user name of this otp
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this otp.
	 *
	 * @param userName the user name of this otp
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this otp.
	 *
	 * @return the create date of this otp
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this otp.
	 *
	 * @param createDate the create date of this otp
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this otp.
	 *
	 * @return the modified date of this otp
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this otp.
	 *
	 * @param modifiedDate the modified date of this otp
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the otp of this otp.
	 *
	 * @return the otp of this otp
	 */
	@AutoEscape
	public String getOtp();

	/**
	 * Sets the otp of this otp.
	 *
	 * @param otp the otp of this otp
	 */
	public void setOtp(String otp);

	/**
	 * Returns the mobile no of this otp.
	 *
	 * @return the mobile no of this otp
	 */
	@AutoEscape
	public String getMobileNo();

	/**
	 * Sets the mobile no of this otp.
	 *
	 * @param mobileNo the mobile no of this otp
	 */
	public void setMobileNo(String mobileNo);

	/**
	 * Returns the email ID of this otp.
	 *
	 * @return the email ID of this otp
	 */
	@AutoEscape
	public String getEmailId();

	/**
	 * Sets the email ID of this otp.
	 *
	 * @param emailId the email ID of this otp
	 */
	public void setEmailId(String emailId);

	/**
	 * Returns the expiry time of this otp.
	 *
	 * @return the expiry time of this otp
	 */
	public Date getExpiryTime();

	/**
	 * Sets the expiry time of this otp.
	 *
	 * @param expiryTime the expiry time of this otp
	 */
	public void setExpiryTime(Date expiryTime);

	/**
	 * Returns the ca number of this otp.
	 *
	 * @return the ca number of this otp
	 */
	@AutoEscape
	public String getCaNumber();

	/**
	 * Sets the ca number of this otp.
	 *
	 * @param caNumber the ca number of this otp
	 */
	public void setCaNumber(String caNumber);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(OTP otp);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OTP> toCacheModel();

	@Override
	public OTP toEscapedModel();

	@Override
	public OTP toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}