create table bsesconn_ConnectionDocument (
	uuid_ VARCHAR(75) null,
	connectionDocumentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	connectionRequestId LONG,
	documentType VARCHAR(75) null,
	documentName VARCHAR(75) null,
	documentPath VARCHAR(75) null,
	transfered VARCHAR(75) null
);

create table bsesconn_ConnectionRequest (
	uuid_ VARCHAR(75) null,
	connectionRequestId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	requestNo VARCHAR(75) null,
	mobileNo VARCHAR(75) null,
	emailId VARCHAR(75) null,
	requestDate DATE null,
	requestType VARCHAR(75) null,
	consumerType VARCHAR(75) null,
	title VARCHAR(75) null,
	firstName VARCHAR(75) null,
	middleName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	sonDaughterWife VARCHAR(75) null,
	fatherOrHusbandName VARCHAR(75) null,
	firmName VARCHAR(75) null,
	signatoryName VARCHAR(75) null,
	signatoryDesignation VARCHAR(75) null,
	organizationType VARCHAR(75) null,
	incorporationDate DATE null,
	gstIn VARCHAR(75) null,
	panNo VARCHAR(75) null,
	locality VARCHAR(75) null,
	district VARCHAR(75) null,
	houseNo VARCHAR(75) null,
	floor VARCHAR(75) null,
	buildingName VARCHAR(75) null,
	street VARCHAR(75) null,
	colonyArea VARCHAR(75) null,
	landmark VARCHAR(75) null,
	landmarkDetails VARCHAR(75) null,
	pinCode VARCHAR(75) null,
	connectionType VARCHAR(75) null,
	tariffCategory VARCHAR(75) null,
	loadKva DOUBLE,
	loadKw DOUBLE,
	areaType VARCHAR(75) null,
	premisesType VARCHAR(75) null,
	upicAvailable BOOLEAN,
	upic VARCHAR(75) null,
	wiringTest BOOLEAN,
	wiringCertificate VARCHAR(75) null,
	elcbInstalled BOOLEAN,
	elcbDocument VARCHAR(75) null,
	stiltParking BOOLEAN,
	height15Mtr BOOLEAN,
	height17Mtr BOOLEAN,
	fcc BOOLEAN,
	fccCertificate VARCHAR(75) null,
	lift BOOLEAN,
	liftCertificate VARCHAR(75) null,
	agriConsumer BOOLEAN,
	hasBdoCertificate BOOLEAN,
	bdoCertificate VARCHAR(75) null,
	hasDpccCertificate BOOLEAN,
	dpccCertificate VARCHAR(75) null,
	hasPollutionCertificate BOOLEAN,
	pollutionCertificate VARCHAR(75) null,
	eServiceOnMail BOOLEAN,
	eServiceMailId VARCHAR(75) null,
	applicantPhoto VARCHAR(75) null,
	applicantSignature LONG,
	idProofType VARCHAR(75) null,
	idProofNo VARCHAR(75) null,
	idProofDocument VARCHAR(75) null,
	ownershipProofType VARCHAR(75) null,
	ownershipProofDocument VARCHAR(75) null,
	selfDeclaration BOOLEAN,
	selfDeclarationTime DATE null,
	bpNumber VARCHAR(75) null,
	orderNo VARCHAR(75) null,
	documentUploaded VARCHAR(75) null,
	sapOrderGenerated VARCHAR(75) null
);

create table bsesconn_LocalityDivision (
	uuid_ VARCHAR(75) null,
	localityDivisionId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	localityName VARCHAR(75) null,
	divisionCode VARCHAR(75) null,
	divisionName VARCHAR(75) null,
	complaintCenter VARCHAR(75) null
);

create table bsesconn_OTP (
	uuid_ VARCHAR(75) null,
	otpId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	otp VARCHAR(75) null,
	mobileNo VARCHAR(75) null,
	emailId VARCHAR(75) null,
	expiryTime DATE null
);