/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bses.connection2.service.base;

import com.bses.connection2.model.LocalityDivision;
import com.bses.connection2.service.LocalityDivisionLocalService;
import com.bses.connection2.service.LocalityDivisionLocalServiceUtil;
import com.bses.connection2.service.persistence.ConnectionDocumentPersistence;
import com.bses.connection2.service.persistence.ConnectionRequestPersistence;
import com.bses.connection2.service.persistence.LocalityDivisionPersistence;
import com.bses.connection2.service.persistence.OTPPersistence;

import com.liferay.asset.kernel.service.persistence.AssetEntryPersistence;
import com.liferay.asset.kernel.service.persistence.AssetTagPersistence;
import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the locality division local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.bses.connection2.service.impl.LocalityDivisionLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.bses.connection2.service.impl.LocalityDivisionLocalServiceImpl
 * @generated
 */
public abstract class LocalityDivisionLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, LocalityDivisionLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LocalityDivisionLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>LocalityDivisionLocalServiceUtil</code>.
	 */

	/**
	 * Adds the locality division to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LocalityDivisionLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param localityDivision the locality division
	 * @return the locality division that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LocalityDivision addLocalityDivision(
		LocalityDivision localityDivision) {

		localityDivision.setNew(true);

		return localityDivisionPersistence.update(localityDivision);
	}

	/**
	 * Creates a new locality division with the primary key. Does not add the locality division to the database.
	 *
	 * @param localityDivisionId the primary key for the new locality division
	 * @return the new locality division
	 */
	@Override
	@Transactional(enabled = false)
	public LocalityDivision createLocalityDivision(long localityDivisionId) {
		return localityDivisionPersistence.create(localityDivisionId);
	}

	/**
	 * Deletes the locality division with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LocalityDivisionLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param localityDivisionId the primary key of the locality division
	 * @return the locality division that was removed
	 * @throws PortalException if a locality division with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LocalityDivision deleteLocalityDivision(long localityDivisionId)
		throws PortalException {

		return localityDivisionPersistence.remove(localityDivisionId);
	}

	/**
	 * Deletes the locality division from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LocalityDivisionLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param localityDivision the locality division
	 * @return the locality division that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LocalityDivision deleteLocalityDivision(
		LocalityDivision localityDivision) {

		return localityDivisionPersistence.remove(localityDivision);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			LocalityDivision.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return localityDivisionPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.bses.connection2.model.impl.LocalityDivisionModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return localityDivisionPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.bses.connection2.model.impl.LocalityDivisionModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return localityDivisionPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return localityDivisionPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return localityDivisionPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public LocalityDivision fetchLocalityDivision(long localityDivisionId) {
		return localityDivisionPersistence.fetchByPrimaryKey(
			localityDivisionId);
	}

	/**
	 * Returns the locality division matching the UUID and group.
	 *
	 * @param uuid the locality division's UUID
	 * @param groupId the primary key of the group
	 * @return the matching locality division, or <code>null</code> if a matching locality division could not be found
	 */
	@Override
	public LocalityDivision fetchLocalityDivisionByUuidAndGroupId(
		String uuid, long groupId) {

		return localityDivisionPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the locality division with the primary key.
	 *
	 * @param localityDivisionId the primary key of the locality division
	 * @return the locality division
	 * @throws PortalException if a locality division with the primary key could not be found
	 */
	@Override
	public LocalityDivision getLocalityDivision(long localityDivisionId)
		throws PortalException {

		return localityDivisionPersistence.findByPrimaryKey(localityDivisionId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			localityDivisionLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LocalityDivision.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("localityDivisionId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			localityDivisionLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(LocalityDivision.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"localityDivisionId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			localityDivisionLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LocalityDivision.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("localityDivisionId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<LocalityDivision>() {

				@Override
				public void performAction(LocalityDivision localityDivision)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, localityDivision);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(LocalityDivision.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return localityDivisionLocalService.deleteLocalityDivision(
			(LocalityDivision)persistedModel);
	}

	public BasePersistence<LocalityDivision> getBasePersistence() {
		return localityDivisionPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return localityDivisionPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the locality divisions matching the UUID and company.
	 *
	 * @param uuid the UUID of the locality divisions
	 * @param companyId the primary key of the company
	 * @return the matching locality divisions, or an empty list if no matches were found
	 */
	@Override
	public List<LocalityDivision> getLocalityDivisionsByUuidAndCompanyId(
		String uuid, long companyId) {

		return localityDivisionPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of locality divisions matching the UUID and company.
	 *
	 * @param uuid the UUID of the locality divisions
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of locality divisions
	 * @param end the upper bound of the range of locality divisions (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching locality divisions, or an empty list if no matches were found
	 */
	@Override
	public List<LocalityDivision> getLocalityDivisionsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<LocalityDivision> orderByComparator) {

		return localityDivisionPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the locality division matching the UUID and group.
	 *
	 * @param uuid the locality division's UUID
	 * @param groupId the primary key of the group
	 * @return the matching locality division
	 * @throws PortalException if a matching locality division could not be found
	 */
	@Override
	public LocalityDivision getLocalityDivisionByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return localityDivisionPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the locality divisions.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.bses.connection2.model.impl.LocalityDivisionModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of locality divisions
	 * @param end the upper bound of the range of locality divisions (not inclusive)
	 * @return the range of locality divisions
	 */
	@Override
	public List<LocalityDivision> getLocalityDivisions(int start, int end) {
		return localityDivisionPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of locality divisions.
	 *
	 * @return the number of locality divisions
	 */
	@Override
	public int getLocalityDivisionsCount() {
		return localityDivisionPersistence.countAll();
	}

	/**
	 * Updates the locality division in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LocalityDivisionLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param localityDivision the locality division
	 * @return the locality division that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LocalityDivision updateLocalityDivision(
		LocalityDivision localityDivision) {

		return localityDivisionPersistence.update(localityDivision);
	}

	/**
	 * Returns the connection document local service.
	 *
	 * @return the connection document local service
	 */
	public com.bses.connection2.service.ConnectionDocumentLocalService
		getConnectionDocumentLocalService() {

		return connectionDocumentLocalService;
	}

	/**
	 * Sets the connection document local service.
	 *
	 * @param connectionDocumentLocalService the connection document local service
	 */
	public void setConnectionDocumentLocalService(
		com.bses.connection2.service.ConnectionDocumentLocalService
			connectionDocumentLocalService) {

		this.connectionDocumentLocalService = connectionDocumentLocalService;
	}

	/**
	 * Returns the connection document persistence.
	 *
	 * @return the connection document persistence
	 */
	public ConnectionDocumentPersistence getConnectionDocumentPersistence() {
		return connectionDocumentPersistence;
	}

	/**
	 * Sets the connection document persistence.
	 *
	 * @param connectionDocumentPersistence the connection document persistence
	 */
	public void setConnectionDocumentPersistence(
		ConnectionDocumentPersistence connectionDocumentPersistence) {

		this.connectionDocumentPersistence = connectionDocumentPersistence;
	}

	/**
	 * Returns the connection request local service.
	 *
	 * @return the connection request local service
	 */
	public com.bses.connection2.service.ConnectionRequestLocalService
		getConnectionRequestLocalService() {

		return connectionRequestLocalService;
	}

	/**
	 * Sets the connection request local service.
	 *
	 * @param connectionRequestLocalService the connection request local service
	 */
	public void setConnectionRequestLocalService(
		com.bses.connection2.service.ConnectionRequestLocalService
			connectionRequestLocalService) {

		this.connectionRequestLocalService = connectionRequestLocalService;
	}

	/**
	 * Returns the connection request persistence.
	 *
	 * @return the connection request persistence
	 */
	public ConnectionRequestPersistence getConnectionRequestPersistence() {
		return connectionRequestPersistence;
	}

	/**
	 * Sets the connection request persistence.
	 *
	 * @param connectionRequestPersistence the connection request persistence
	 */
	public void setConnectionRequestPersistence(
		ConnectionRequestPersistence connectionRequestPersistence) {

		this.connectionRequestPersistence = connectionRequestPersistence;
	}

	/**
	 * Returns the locality division local service.
	 *
	 * @return the locality division local service
	 */
	public LocalityDivisionLocalService getLocalityDivisionLocalService() {
		return localityDivisionLocalService;
	}

	/**
	 * Sets the locality division local service.
	 *
	 * @param localityDivisionLocalService the locality division local service
	 */
	public void setLocalityDivisionLocalService(
		LocalityDivisionLocalService localityDivisionLocalService) {

		this.localityDivisionLocalService = localityDivisionLocalService;
	}

	/**
	 * Returns the locality division persistence.
	 *
	 * @return the locality division persistence
	 */
	public LocalityDivisionPersistence getLocalityDivisionPersistence() {
		return localityDivisionPersistence;
	}

	/**
	 * Sets the locality division persistence.
	 *
	 * @param localityDivisionPersistence the locality division persistence
	 */
	public void setLocalityDivisionPersistence(
		LocalityDivisionPersistence localityDivisionPersistence) {

		this.localityDivisionPersistence = localityDivisionPersistence;
	}

	/**
	 * Returns the otp local service.
	 *
	 * @return the otp local service
	 */
	public com.bses.connection2.service.OTPLocalService getOTPLocalService() {
		return otpLocalService;
	}

	/**
	 * Sets the otp local service.
	 *
	 * @param otpLocalService the otp local service
	 */
	public void setOTPLocalService(
		com.bses.connection2.service.OTPLocalService otpLocalService) {

		this.otpLocalService = otpLocalService;
	}

	/**
	 * Returns the otp persistence.
	 *
	 * @return the otp persistence
	 */
	public OTPPersistence getOTPPersistence() {
		return otpPersistence;
	}

	/**
	 * Sets the otp persistence.
	 *
	 * @param otpPersistence the otp persistence
	 */
	public void setOTPPersistence(OTPPersistence otpPersistence) {
		this.otpPersistence = otpPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the asset entry local service.
	 *
	 * @return the asset entry local service
	 */
	public com.liferay.asset.kernel.service.AssetEntryLocalService
		getAssetEntryLocalService() {

		return assetEntryLocalService;
	}

	/**
	 * Sets the asset entry local service.
	 *
	 * @param assetEntryLocalService the asset entry local service
	 */
	public void setAssetEntryLocalService(
		com.liferay.asset.kernel.service.AssetEntryLocalService
			assetEntryLocalService) {

		this.assetEntryLocalService = assetEntryLocalService;
	}

	/**
	 * Returns the asset entry persistence.
	 *
	 * @return the asset entry persistence
	 */
	public AssetEntryPersistence getAssetEntryPersistence() {
		return assetEntryPersistence;
	}

	/**
	 * Sets the asset entry persistence.
	 *
	 * @param assetEntryPersistence the asset entry persistence
	 */
	public void setAssetEntryPersistence(
		AssetEntryPersistence assetEntryPersistence) {

		this.assetEntryPersistence = assetEntryPersistence;
	}

	/**
	 * Returns the asset tag local service.
	 *
	 * @return the asset tag local service
	 */
	public com.liferay.asset.kernel.service.AssetTagLocalService
		getAssetTagLocalService() {

		return assetTagLocalService;
	}

	/**
	 * Sets the asset tag local service.
	 *
	 * @param assetTagLocalService the asset tag local service
	 */
	public void setAssetTagLocalService(
		com.liferay.asset.kernel.service.AssetTagLocalService
			assetTagLocalService) {

		this.assetTagLocalService = assetTagLocalService;
	}

	/**
	 * Returns the asset tag persistence.
	 *
	 * @return the asset tag persistence
	 */
	public AssetTagPersistence getAssetTagPersistence() {
		return assetTagPersistence;
	}

	/**
	 * Sets the asset tag persistence.
	 *
	 * @param assetTagPersistence the asset tag persistence
	 */
	public void setAssetTagPersistence(
		AssetTagPersistence assetTagPersistence) {

		this.assetTagPersistence = assetTagPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.bses.connection2.model.LocalityDivision",
			localityDivisionLocalService);

		_setLocalServiceUtilService(localityDivisionLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.bses.connection2.model.LocalityDivision");

		_setLocalServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LocalityDivisionLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LocalityDivision.class;
	}

	protected String getModelClassName() {
		return LocalityDivision.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = localityDivisionPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		LocalityDivisionLocalService localityDivisionLocalService) {

		try {
			Field field =
				LocalityDivisionLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, localityDivisionLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(
		type = com.bses.connection2.service.ConnectionDocumentLocalService.class
	)
	protected com.bses.connection2.service.ConnectionDocumentLocalService
		connectionDocumentLocalService;

	@BeanReference(type = ConnectionDocumentPersistence.class)
	protected ConnectionDocumentPersistence connectionDocumentPersistence;

	@BeanReference(
		type = com.bses.connection2.service.ConnectionRequestLocalService.class
	)
	protected com.bses.connection2.service.ConnectionRequestLocalService
		connectionRequestLocalService;

	@BeanReference(type = ConnectionRequestPersistence.class)
	protected ConnectionRequestPersistence connectionRequestPersistence;

	@BeanReference(type = LocalityDivisionLocalService.class)
	protected LocalityDivisionLocalService localityDivisionLocalService;

	@BeanReference(type = LocalityDivisionPersistence.class)
	protected LocalityDivisionPersistence localityDivisionPersistence;

	@BeanReference(type = com.bses.connection2.service.OTPLocalService.class)
	protected com.bses.connection2.service.OTPLocalService otpLocalService;

	@BeanReference(type = OTPPersistence.class)
	protected OTPPersistence otpPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	@ServiceReference(
		type = com.liferay.asset.kernel.service.AssetEntryLocalService.class
	)
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@ServiceReference(type = AssetEntryPersistence.class)
	protected AssetEntryPersistence assetEntryPersistence;

	@ServiceReference(
		type = com.liferay.asset.kernel.service.AssetTagLocalService.class
	)
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

	@ServiceReference(type = AssetTagPersistence.class)
	protected AssetTagPersistence assetTagPersistence;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}