/**
 * WebGISServiceSoap.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.bses.sap.ws;

public interface WebGISServiceSoap extends java.rmi.Remote {
    public com.bses.sap.ws.Get_Area_Details_forLcdResponseGet_Area_Details_forLcdResult get_Area_Details_forLcd(java.lang.String objectid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetassetreportbydivResponseGetassetreportbydivResult getassetreportbydiv(java.lang.String divcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetSensorOIL_TEMPHyperlinkResponseGetSensorOIL_TEMPHyperlinkResult getSensorOIL_TEMPHyperlink(java.lang.String IMEINO, java.lang.String DTTYPE) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetSensorR_TEMPHyperlinkResponseGetSensorR_TEMPHyperlinkResult getSensorR_TEMPHyperlink(java.lang.String IMEINO, java.lang.String DTTYPE) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetSensorY_TEMPHyperlinkResponseGetSensorY_TEMPHyperlinkResult getSensorY_TEMPHyperlink(java.lang.String IMEINO, java.lang.String DTTYPE) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetSensorB_TEMPHyperlinkResponseGetSensorB_TEMPHyperlinkResult getSensorB_TEMPHyperlink(java.lang.String IMEINO, java.lang.String DTTYPE) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetSensorN_TEMPHyperlinkResponseGetSensorN_TEMPHyperlinkResult getSensorN_TEMPHyperlink(java.lang.String IMEINO, java.lang.String DTTYPE) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_EHVstatus_list_1ResponseGet_EHVstatus_list_1Result get_EHVstatus_list_1(java.lang.String gridid, java.lang.String feederkv, java.lang.String[] feederid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_EHV11Status_listResponseGet_EHV11Status_listResult get_EHV11Status_list(java.lang.String gridid, java.lang.String[] ptcd, java.lang.String feederkv, java.lang.String[] feederid) throws java.rmi.RemoteException;
    public java.lang.String get_Areabypole(java.lang.String polestr) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_PoleDetails_2ResponseGet_PoleDetails_2Result get_PoleDetails_2(java.lang.String gridid, java.lang.String feederid, java.lang.String sapfunctio, java.lang.String dtcode, java.lang.String ltfeeder) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_poleDeatils_3ResponseGet_poleDeatils_3Result get_poleDeatils_3(java.lang.String dtcode) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_ConsumerPoleDetails_2ResponseGet_ConsumerPoleDetails_2Result get_ConsumerPoleDetails_2(java.lang.String gridid, java.lang.String feederid, java.lang.String sapfunctio, java.lang.String dtcode, java.lang.String ltfeeder) throws java.rmi.RemoteException;
    public java.lang.String get_Areabypole_2Consumer(java.lang.String polestr) throws java.rmi.RemoteException;
    public java.lang.String[] get_Areabypole_2(java.lang.String polestr) throws java.rmi.RemoteException;
    public java.lang.String[] get_AreabyDT(java.lang.String polestr) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_status_listResponseGet_status_listResult get_status_list(java.lang.String gridid, java.lang.String feederid, java.lang.String[] subsid, java.lang.String[] dtid, java.lang.String[] ltfdrid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_AutoTrip_feederdetailsResponseGet_AutoTrip_feederdetailsResult get_AutoTrip_feederdetails(java.lang.String switchid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_HT_feederSection_varResponseGet_HT_feederSection_varResult get_HT_feederSection_var(java.lang.String feederid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_HTgridlistResponseGet_HTgridlistResult get_HTgridlist(java.lang.String divcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_HTgridlist_varResponseGet_HTgridlist_varResult get_HTgridlist_var(java.lang.String divcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_HTgridlist_varAllDivisionsResponseGet_HTgridlist_varAllDivisionsResult get_HTgridlist_varAllDivisions(java.lang.String divcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_HT_feederlist_varAllDivisionsResponseGet_HT_feederlist_varAllDivisionsResult get_HT_feederlist_varAllDivisions(java.lang.String stationfac, java.lang.String divcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_PolelistResponseGet_PolelistResult get_Polelist(java.lang.String ltfeedercode) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_backfeedlist_feederResponseGet_backfeedlist_feederResult get_backfeedlist_feeder(java.lang.String feederidz) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Cable_sectionResponseGet_Cable_sectionResult get_Cable_section(java.lang.String feederid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Cable_section_CloseResponseGet_Cable_section_CloseResult get_Cable_section_Close(java.lang.String feederid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_EHVstatus_listResponseGet_EHVstatus_listResult get_EHVstatus_list(java.lang.String gridid, java.lang.String feederkv, java.lang.String[] feederid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Area_Details_forconstituencyResponseGet_Area_Details_forconstituencyResult get_Area_Details_forconstituency(java.lang.String objectid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetMidasDisc_dataResponseGetMidasDisc_dataResult getMidasDisc_data(java.lang.String div) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetSubstationDetailsPIsurveyResponseGetSubstationDetailsPIsurveyResult getSubstationDetailsPIsurvey(java.lang.String facilityid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_ConsumerListMultipleResponseGet_ConsumerListMultipleResult get_ConsumerListMultiple(java.lang.String poleid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Poles_From_SubstationsResponseGet_Poles_From_SubstationsResult get_Poles_From_Substations(java.lang.String ltfeederid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetRMUDetailsPIResponseGetRMUDetailsPIResult getRMUDetailsPI(java.lang.String subsid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_ComplaintCenter_ContactNoResponseGet_ComplaintCenter_ContactNoResult get_ComplaintCenter_ContactNo(java.lang.String ccId) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_ConsumerLoadResponseGet_ConsumerLoadResult get_ConsumerLoad(java.lang.String[] ltFDRList) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetPolesbyAreaResponseGetPolesbyAreaResult getPolesbyArea(java.lang.String areas) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_dtAreaResponseGet_dtAreaResult get_dtArea(java.lang.String SAPFUNCTIO, java.lang.String poleno, java.lang.String CANumber) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_AreaforCAResponseGet_AreaforCAResult get_AreaforCA(java.lang.String DT, java.lang.String SAPFUNCTIO, java.lang.String poleno, java.lang.String CANumber) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Z_BAPI_DSS_ISU_CA_DISPLAYResponseZ_BAPI_DSS_ISU_CA_DISPLAYResult z_BAPI_DSS_ISU_CA_DISPLAY(java.lang.String strCANumber) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_BD_DetailsResponseGet_BD_DetailsResult get_BD_Details(java.lang.String externalId) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Company_listResponseGet_Company_listResult get_Company_list() throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Circle_listResponseGet_Circle_listResult get_Circle_list(java.lang.String company) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_CirclebyDivisionResponseGet_CirclebyDivisionResult get_CirclebyDivision(java.lang.String divisionName) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Circle_DetailsResponseGet_Circle_DetailsResult get_Circle_Details(java.lang.String circle) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Division_listResponseGet_Division_listResult get_Division_list(java.lang.String circle) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Affected_ConsumerAndLoadResponseGet_Affected_ConsumerAndLoadResult get_Affected_ConsumerAndLoad(java.lang.String dtlist) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Division_detailsResponseGet_Division_detailsResult get_Division_details(java.lang.String division_code) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Sub_Division_listResponseGet_Sub_Division_listResult get_Sub_Division_list(java.lang.String divsionCode) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Sub_Division_detailsResponseGet_Sub_Division_detailsResult get_Sub_Division_details(java.lang.String subdivision_code) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Area_listResponseGet_Area_listResult get_Area_list(java.lang.String divcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_ltfeederlistResponseGet_ltfeederlistResult get_ltfeederlist(java.lang.String DTequipmentcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Cable_sectionHTResponseGet_Cable_sectionHTResult get_Cable_sectionHT(java.lang.String feederid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Cable_sectionltResponseGet_Cable_sectionltResult get_Cable_sectionlt(java.lang.String feederid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Complaint_Center_listResponseGet_Complaint_Center_listResult get_Complaint_Center_list(java.lang.String divisioncode) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_area_details_CircleResponseGet_area_details_CircleResult get_area_details_Circle(java.lang.String objectid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_EHVfeederName_1ResponseGet_EHVfeederName_1Result get_EHVfeederName_1(java.lang.String[] feederid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_EHVPTlistResponseGet_EHVPTlistResult get_EHVPTlist(java.lang.String gridid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_EHVgridlistResponseGet_EHVgridlistResult get_EHVgridlist(java.lang.String circle) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_PoleDetailsbyltfeederResponseGet_PoleDetailsbyltfeederResult get_PoleDetailsbyltfeeder(java.lang.String LTFeeder) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Poles_From_LTFeedersResponseGet_Poles_From_LTFeedersResult get_Poles_From_LTFeeders(java.lang.String LTFeeders) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Area_DetailsmultiplebydivResponseGet_Area_DetailsmultiplebydivResult get_Area_Detailsmultiplebydiv(java.lang.String objectid, java.lang.String division) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Subslist_varResponseGet_Subslist_varResult get_Subslist_var(java.lang.String divcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Complaint_Center_DetailsResponseGet_Complaint_Center_DetailsResult get_Complaint_Center_Details(java.lang.String complaintCentre) throws java.rmi.RemoteException;
    public com.bses.sap.ws.ComplaintStatusResponseComplaintStatusResult complaintStatus(java.lang.String complaintNoOR_CANo) throws java.rmi.RemoteException;
    public com.bses.sap.ws.ComplaintStatusDetailsResponseComplaintStatusDetailsResult complaintStatusDetails(java.lang.String CA) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetFaultCatResponseGetFaultCatResult getFaultCat() throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetSubFaultCatResponseGetSubFaultCatResult getSubFaultCat(java.lang.String category) throws java.rmi.RemoteException;
    public com.bses.sap.ws.ComplaintRegistrationAppResponseComplaintRegistrationAppResult complaintRegistrationApp(java.lang.String key, java.lang.String callerName, java.lang.String phone, java.lang.String add, java.lang.String email, java.lang.String CA, java.lang.String area, java.lang.String faultCategoryCode, java.lang.String subFaultCategoryName, java.lang.String remarks, java.lang.String CODE) throws java.rmi.RemoteException;
    public com.bses.sap.ws.ComplaintRegistrationWeb_AreaResponseComplaintRegistrationWeb_AreaResult complaintRegistrationWeb_Area(java.lang.String areaName, java.lang.String callerName, java.lang.String callerPhone, java.lang.String address, java.lang.String FAULT_CAT, java.lang.String FAULT_TYPE, java.lang.String comp_Center_Code, java.lang.String circle, java.lang.String division, java.lang.String AREA_OBJECTID, java.lang.String st_Light_Location, java.lang.String remarks, java.lang.String source) throws java.rmi.RemoteException;
    public com.bses.sap.ws.ComplaintRegistrationWebResponseComplaintRegistrationWebResult complaintRegistrationWeb(java.lang.String key, java.lang.String callerName, java.lang.String phone, java.lang.String add, java.lang.String email, java.lang.String CA, java.lang.String area, java.lang.String faultCategoryCode, java.lang.String subFaultCategoryName, java.lang.String remarks, java.lang.String CODE, java.lang.String poleNum) throws java.rmi.RemoteException;
    public com.bses.sap.ws.BRPL_OutletResponseBRPL_OutletResult BRPL_Outlet() throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_substationindivResponseGet_substationindivResult get_substationindiv(java.lang.String divcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetSubstationlistResponseGetSubstationlistResult getSubstationlist(java.lang.String subdivision) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetSubstationDetailsforsurveyResponseGetSubstationDetailsforsurveyResult getSubstationDetailsforsurvey(java.lang.String facilityid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_SubstationDetailsby_divResponseGet_SubstationDetailsby_divResult get_SubstationDetailsby_div(java.lang.String divcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_substation_detailsResponseGet_substation_detailsResult get_substation_details(java.lang.String stationFacilityid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Poles_From_DTsResponseGet_Poles_From_DTsResult get_Poles_From_DTs(java.lang.String DTID) throws java.rmi.RemoteException;
    public java.lang.String forFeedername(java.lang.String feederid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Feeder_StatusResponseGet_Feeder_StatusResult get_Feeder_Status(java.lang.String swids) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_ltfeederlist1ResponseGet_ltfeederlist1Result get_ltfeederlist1(java.lang.String dtcode) throws java.rmi.RemoteException;
    public java.lang.String get_cablesinltfdr(java.lang.String ltfdrcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Cable_sectionlt1ResponseGet_Cable_sectionlt1Result get_Cable_sectionlt1(java.lang.String ltfdrID) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_backfeedlist_dtResponseGet_backfeedlist_dtResult get_backfeedlist_dt(java.lang.String[] dtcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Cable_section_detailResponseGet_Cable_section_detailResult get_Cable_section_detail(java.lang.String cblID) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Cable_section_detail1ResponseGet_Cable_section_detail1Result get_Cable_section_detail1(java.lang.String cblID) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetfeedernameResponseGetfeedernameResult getfeedername() throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetfeederNMResponseGetfeederNMResult getfeederNM(java.lang.String feederid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetDTNameResponseGetDTNameResult getDTName(java.lang.String dt) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetCircuitBySubstationResponseGetCircuitBySubstationResult getCircuitBySubstation(java.lang.String substation) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_dtlistResponseGet_dtlistResult get_dtlist(java.lang.String SAPFUNCTIO) throws java.rmi.RemoteException;
    public com.bses.sap.ws.For_DT_FirResponseFor_DT_FirResult for_DT_Fir(java.lang.String stationFacilityid, java.lang.String dtcode) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetacbResponseGetacbResult getacb(java.lang.String subsid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.ValidatepoleResponseValidatepoleResult validatepole(java.lang.String poleno) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetCADetailsResponseGetCADetailsResult getCADetails(java.lang.String ca) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_feederpillarResponseGet_feederpillarResult get_feederpillar(java.lang.String ltfeederid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_HT_feederlistResponseGet_HT_feederlistResult get_HT_feederlist(java.lang.String stationfac, java.lang.String divcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_EHVfeederlist_1ResponseGet_EHVfeederlist_1Result get_EHVfeederlist_1(java.lang.String gridcd, java.lang.String feederkv) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_EHVfeederlist_TestResponseGet_EHVfeederlist_TestResult get_EHVfeederlist_Test() throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_Area_list1ResponseGet_Area_list1Result get_Area_list1(java.lang.String divcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_EHV11FeederlistResponseGet_EHV11FeederlistResult get_EHV11Feederlist(java.lang.String ptcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetgridnameResponseGetgridnameResult getgridname() throws java.rmi.RemoteException;
    public com.bses.sap.ws.Getgridname1ResponseGetgridname1Result getgridname1() throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetCCfromZoneResponseGetCCfromZoneResult getCCfromZone(java.lang.String zoneID) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_EHVfeederlist_2ResponseGet_EHVfeederlist_2Result get_EHVfeederlist_2(java.lang.String gridcd, java.lang.String feederkv) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_HT_feederlist_varResponseGet_HT_feederlist_varResult get_HT_feederlist_var(java.lang.String stationfac, java.lang.String divcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetMidas_dataResponseGetMidas_dataResult getMidas_data(java.lang.String div) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Midas_breakdownResponseMidas_breakdownResult midas_breakdown(java.lang.String sapid) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_backfeedlist_substationResponseGet_backfeedlist_substationResult get_backfeedlist_substation(java.lang.String[] sapfunction) throws java.rmi.RemoteException;
    public java.lang.String get_cableslength(java.lang.String sectionid, java.lang.String type) throws java.rmi.RemoteException;
    public java.lang.String get_FDRNames(java.lang.String ltfdrcd) throws java.rmi.RemoteException;
    public com.bses.sap.ws.Get_HTFDRNamesResponseGet_HTFDRNamesResult get_HTFDRNames(java.lang.String feederID) throws java.rmi.RemoteException;
    public com.bses.sap.ws.GetrmuResponseGetrmuResult getrmu(java.lang.String subsid) throws java.rmi.RemoteException;
}
